---
configs:
  use: default
  default:
    box: rockylinux/8             # The Base Box, don't recommend changing it
    version: 4.0.0                # Box version, as updated from time to time
    hostname: YOUR_HOST           # The hostname of the vm you are creating
    ram: 4096                     # The virtual ram to allocate the vm
    cores: 2                      # The virtual cores to allocate the bm
    private-ip: 192.168.33.10     # The private IP you wish to assign the box, really it can be anything
    timezone: America/New_York    # The timezone to assign the vm
    user: YOUR_USER_NAME          # The username to create on the vm
    code-srv-pass: YOUR_PASSWORD  # The password you will use to log into code-server
    node-version: 16              # The nodejs version to install, valid options are: 10, 12, 13, 14, 16, 16-epel (see: dnf module list nodejs)
    public-key-path: C:/Users/YOUR_USER_NAME/.ssh/id_rsa.pub  # Path to the public key which will be hoisted to the vm
    private-key-path: C:/Users/YOUR_USER_NAME/.ssh/id_rsa     # Path to the private key to use to connect with ssh